/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as TrainingsIndexRouteImport } from './routes/trainings.index'
import { Route as TrainingsTrainingIdRouteImport } from './routes/trainings.$trainingId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingsIndexRoute = TrainingsIndexRouteImport.update({
  id: '/trainings/',
  path: '/trainings/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingsTrainingIdRoute = TrainingsTrainingIdRouteImport.update({
  id: '/trainings/$trainingId',
  path: '/trainings/$trainingId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/trainings/$trainingId': typeof TrainingsTrainingIdRoute
  '/trainings/': typeof TrainingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/trainings/$trainingId': typeof TrainingsTrainingIdRoute
  '/trainings': typeof TrainingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/trainings/$trainingId': typeof TrainingsTrainingIdRoute
  '/trainings/': typeof TrainingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/trainings/$trainingId' | '/trainings/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/trainings/$trainingId' | '/trainings'
  id: '__root__' | '/' | '/auth' | '/trainings/$trainingId' | '/trainings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  TrainingsTrainingIdRoute: typeof TrainingsTrainingIdRoute
  TrainingsIndexRoute: typeof TrainingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainings/': {
      id: '/trainings/'
      path: '/trainings'
      fullPath: '/trainings/'
      preLoaderRoute: typeof TrainingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainings/$trainingId': {
      id: '/trainings/$trainingId'
      path: '/trainings/$trainingId'
      fullPath: '/trainings/$trainingId'
      preLoaderRoute: typeof TrainingsTrainingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  TrainingsTrainingIdRoute: TrainingsTrainingIdRoute,
  TrainingsIndexRoute: TrainingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
